// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBuisnessVTCO.Data;

namespace MyBuisnessVTCO.Migrations
{
    [DbContext(typeof(BuisnessContext))]
    partial class BuisnessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyBuisnessVTCO.Models.Truck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("A_Immatriculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Kilometrage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Marque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Carrosserie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Chassis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_ComForfait")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_PrixMiniClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_VNC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumChassis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("V_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V_Gamme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V_Modele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V_Moteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V_Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
